SELECT * FROM SYSCAT.BUFFERPOOLS P;

SELECT * FROM SYSCAT.TABLESPACES T

SELECT * FROM SYSCAT.STOGROUPS;

SELECT * FROM SYSCAT.TABLES;

SELECT * FROM TABLE(MON_GET_BUFFERPOOL(NULL, -1)) T;

SELECT * FROM TABLE(MON_GET_TABLESPACE(NULL, -1)) T;

SELECT * FROM TABLE(MON_GET_CONTAINER(NULL, -1)) T;
SELECT * FROM SYSCAT.STOGROUPS

SELECT * FROM SYSIBMADM.DBPATHS;

