WITH BASE AS (
SELECT *
FROM (VALUES ('CROTBS','04','08',DATE('2014-12-01'),DATE('2019-12-01'))) 
                AS T(NOME, PAGETBS,EXTENTS,DATAINICIAL, DATAFINAL)
)
,CTEREC (DATA) AS (
SELECT B.DATAINICIAL AS DATA
FROM BASE B
UNION ALL 
SELECT C.DATA + 1 MONTH AS DATA
FROM CTEREC C
WHERE C.DATA < (SELECT DATAFINAL FROM BASE)
)
SELECT 'CREATE TABLESPACE '
        || (SELECT NOME FROM BASE) || TO_CHAR(C.DATA, 'YYYYMM') || '_' || (SELECT PAGETBS || EXTENTS FROM BASE) -- Dia e Mes
        --|| (SELECT NOME FROM BASE) || TO_CHAR(C.DATA, 'YYYYMMDD') || '_' || (SELECT PAGETBS || EXTENTS FROM BASE) --Dia,Mes e Ano
        --|| (SELECT NOME FROM BASE) || TO_DATE(C.DATA, 'RRRR-MM-DD') || '_' || (SELECT PAGETBS || EXTENTS FROM BASE) --Timestamp
        || ' PAGESIZE ' || (SELECT PAGETBS FROM BASE) || 'K' 
        || ' EXTENTSIZE ' || (SELECT EXTENTS FROM BASE)
        || ' NO FILE SYSTEM CACHING'
        || ' BUFFERPOOL ' || (SELECT BPNAME 
                                FROM SYSCAT.BUFFERPOOLS BP
                                INNER JOIN BASE BA
                                        ON (BP.PAGESIZE / 1024) = INT(BA.PAGETBS)
                            FETCH FIRST 1 ROWS ONLY)
        AS COMANDO
FROM CTEREC C
ORDER BY 1
